### ISSUE TITLE
Released Version Download

### ISSUE THREAD

**Issue by kerbroasted** [rams3sh/cuw#1]
Where can I find the released version?

**Comment by rams3sh** [comment]
Hey @nullsession0x , 

I dont maintain this repo any more. Its been some time , I tested the code. 

You would have to download the raw script and use it as is and follow the README.md.

I haven't maintained a release version or a release cycle per say for this code.

**Comment by rams3sh** [comment]
@nullsession0x 

Link: https://github.com/rams3sh/cuw/releases

Just in case you haven't found it already !!

Closing the issue !!
